CREATE SCHEMA blog;

CREATE USER blog_user WITH PASSWORD 'blog_password';

GRANT USAGE ON SCHEMA blog TO blog_user;

GRANT CREATE ON SCHEMA blog TO blog_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA blog GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO blog_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA blog TO blog_user;

CREATE TABLE BLOG.PERSON
(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(200) not NULL,
  CPF VARCHAR(14) NULL,  
  BIRTH DATE NOT NULL,    
  EMAIL VARCHAR(100) NULL,
  TYPE_PERSON CHAR(1) NULL,
  STATUS BOOLEAN DEFAULT TRUE 
);

CREATE TABLE BLOG.USER (
  ID SERIAL PRIMARY KEY,    
  LOGIN VARCHAR(150) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  STATUS BOOLEAN DEFAULT TRUE,
  ID_PERSON INT NOT NULL REFERENCES blog.person(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_login_unique ON blog."user"(login);

CREATE TABLE BLOG.CATEGORY (
  ID SERIAL PRIMARY KEY,
  NM_CATEGORY VARCHAR(50) NOT NULL,
  STATUS BOOLEAN DEFAULT TRUE
);

CREATE TABLE BLOG.POST_STATUS (
  ID SERIAL PRIMARY KEY,
  NM_STATUS VARCHAR(50) NOT NULL,
  STATUS BOOLEAN DEFAULT TRUE
);

CREATE TABLE BLOG.POST (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(65) NOT NULL,  
  SUBTITLE VARCHAR(200) NOT NULL,
  MESSAGE TEXT NOT NULL,  
  IMAGE TEXT NULL,  
  CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATEDBY INT NOT NULL REFERENCES blog.person(id),
  POSTEDAT TIMESTAMP NULL,
  POSTEDBY INT NULL REFERENCES blog.person(id),
  CATEGORY INT NOT NULL REFERENCES blog.category(id),
  POST_STATUS INT NOT NULL REFERENCES blog.post_status(id)
);

CREATE TABLE BLOG.QUESTAO (
  ID SERIAL PRIMARY KEY,
  ENUNCIADO TEXT NOT NULL,  
  RESPOSTA CHAR(1) NOT NULL,    
  ESCOLARIDADE INT NOT NULL,
  TURNO INT NOT NULL,
  PERIODO INT NOT NULL,
  TIPO_QUESTAO INT NOT NULL,
  CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATEDBY INT NOT NULL REFERENCES blog.person(id),
  POSTEDAT TIMESTAMP NULL,
  POSTEDBY INT NULL REFERENCES blog.person(id),
  CATEGORY INT NOT NULL REFERENCES blog.category(id),
  STATUS BOOLEAN DEFAULT TRUE
);

CREATE TABLE BLOG.ALTERNATIVAS (
  ID SERIAL PRIMARY KEY,
  ALTERNATIVA TEXT NOT NULL,
  QUESTAOID INT NOT NULL REFERENCES blog.questao(id) ON DELETE CASCADE
);

CREATE TABLE BLOG.PROVA (
  ID SERIAL PRIMARY KEY,
  DESCRICAO TEXT NOT NULL,
  TEMPO_PROVA INT NOT NULL,
  CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATEDBY INT NOT NULL REFERENCES blog.person(id)
);

-- ALTER TABLE blog.prova ADD COLUMN tempo_prova INT;
-- DROP TABLE BLOG.PROVA_QUESTAO;

CREATE TABLE BLOG.PROVA_QUESTAO (
  ID SERIAL PRIMARY KEY,
  PROVAID INT NOT NULL REFERENCES blog.prova(id) ON DELETE CASCADE,
  QUESTAOID INT NOT NULL REFERENCES blog.questao(id),
  NUMERO_QUESTAO INT NOT NULL,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_prova_questao UNIQUE (provaid, questaoid),
  CONSTRAINT uq_prova_numero UNIQUE (provaid, numero_questao)
);

--ALTER TABLE blog.PROVA_QUESTAO ADD COLUMN createdat TIMESTAMP;

CREATE TABLE BLOG.PROVA_ALUNO (
  id SERIAL PRIMARY KEY,
  provaid INT NOT NULL REFERENCES blog.prova(id) ON DELETE CASCADE,
  alunoid INT NOT NULL REFERENCES blog.person(id),
  status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  nota NUMERIC(5,2) NULL,
  tempo_gasto INT NULL,
  data_inicio TIMESTAMP NULL,
  data_fim TIMESTAMP NULL,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- status: PENDENTE, EM_ANDAMENTO, FINALIZADA, EXPIRADA
-- IMPEDIR O MESMO ALUNO DE FAZER A MESMO PROVA MAIS DE UMA VEZ
-- ALTER TABLE blog.prova_aluno ADD CONSTRAINT uq_prova_aluno UNIQUE (provaid, alunoid);

CREATE TABLE BLOG.PROVA_ALUNO_RESPOSTA (
  id SERIAL PRIMARY KEY,
  prova_aluno_id INT NOT NULL REFERENCES blog.prova_aluno(id) ON DELETE CASCADE,
  questaoid INT NOT NULL REFERENCES blog.questao(id),
  alternativaid INT NULL REFERENCES blog.alternativas(id),
  resposta_letra CHAR(1) NULL,
  correta BOOLEAN null,
  createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--ALTER TABLE blog.PROVA_ALUNO_RESPOSTA ADD COLUMN createdat TIMESTAMP;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA blog TO blog_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA blog GRANT USAGE, SELECT ON SEQUENCES TO blog_user;
